README.md, src/controllers/request-controller.ts
- add basic API validation
- fix `README.md` according to implementation
=> Basic API validation

README.md, src/controllers/anchor-controller.ts, src/controllers/request-controller.ts, src/models/request-status.ts, src/models/request.ts, src/services/anchor-service.ts, src/services/request-service.ts, src/utils.ts
- skip staled requests
- add sorting for Merkle tree
- add `message` for request model
=> Stale requests

package-lock.json, package.json, src/context.ts, src/models/transaction.ts, src/services/blockchain-service.ts, src/utils.ts
- convert chainId to CAIP-2 format
- refactor `Context` implementation
=> CAIP-2 chainID

config/default.json, src/context.ts, src/server.ts, src/services/anchor-service.ts, src/services/blockchain/blockchain-service.ts, src/services/blockchain/ethereum/ethereum-blockchain-service.ts, src/utils.ts
- abstract blockchain service to support other blockchains as well
=> Blockchain service abstraction

.eslintrc.js, babel.config.js, package-lock.json, package.json, src/app.ts, src/context.ts, src/controllers/anchor-controller.ts, src/controllers/request-controller.ts, src/merkle/__tests__/merkle-direct-path.test.ts, src/merkle/__tests__/merkle-layers.test.ts, src/merkle/__tests__/merkle-proof.test.ts, src/merkle/__tests__/merkle-verify-proof.test.ts, src/models/anchor.ts, src/services/anchor-service.ts, src/services/blockchain/blockchain-service.ts, src/services/blockchain/ethereum/ethereum-blockchain-service.ts, src/services/request-service.ts, src/utils.ts, tslint.json
- move tests from `test` directory to relative `__tests__`
- replace `mocha` with `jest`
- replace `tslint` with `eslint`
- fix `convertToUnixTimestamp` util fn
=> Refactor tests + linting

babel.config.js, config/env/development.json, config/env/test.json, package-lock.json, package.json, src/app.ts, src/context.ts, src/merkle/__tests__/merkle-direct-path.test.ts, src/merkle/__tests__/merkle-layers.test.ts, src/merkle/__tests__/merkle-proof.test.ts, src/merkle/__tests__/merkle-verify-proof.test.ts, src/services/blockchain/__tests__/__snapshots__/eth-bc-service.test.ts.snap, src/services/blockchain/__tests__/eth-bc-service.test.ts
- add more configuration options based on `NODE_ENV` variable
- implement anchor test on local (embedded) ganache instance
- add `husky` for `pre-commit` and `pre-push` git hooks
=> Ethereum blockchain unit tests

database.env, docker-compose.yml, ormconfig.json, package-lock.json, package.json, src/controllers/internal-controller.ts, src/controllers/request-controller.ts, src/models/request.ts, src/services/anchor-service.ts, src/services/request-service.ts
- group db related operations into logical transactions
- add `PostgreSQL` support
=> feat(anchor): Change transactional behaviour for db related operations

ormconfig.json, src/controllers/request-controller.ts, src/merkle/merkle-tree.ts, src/services/anchor-service.ts, src/services/blockchain/ethereum/ethereum-blockchain-service.ts
- fix leaf sorting and path matching (appropriate path for leaf)
- minor refactor
=> Merkle leaf sorting fix

.circleci/config.yml
- Implement CircleCi configuration
=> Implement CircleCi configuration

.circleci/config.yml, jest.config.js, package-lock.json, package.json
=> Fix circleci test job

src/services/blockchain/ethereum/ethereum-blockchain-service.ts, src/services/request-service.ts
- fix query for stale requests
- fix ethereum config check
=> Stale requests query fix

src/services/blockchain/ethereum/ethereum-blockchain-service.ts
=> Nonce issue

.gitignore, package-lock.json, src/app.ts, src/context.ts, src/controllers/service-info-controller.ts, src/services/anchor-service.ts, src/services/blockchain/__tests__/eth-bc-service.test.ts, src/services/blockchain/blockchain-service.ts, src/services/blockchain/ethereum/ethereum-blockchain-service.ts, src/services/ceramic-service.ts, src/services/ipfs-service.ts, src/services/request-service.ts
- split `CeramicService` service
- connect to Blockchain before starting the API
- various cleanup
=> CAS cleanup

package-lock.json, package.json
- fix dependency `typeorm-transactional-cls-hooked` dependency.
=> Dependency typeorm-transactional-cls-hooked issue

package.json, src/services/ipfs-service.ts
=> IPFS get cache

package-lock.json, package.json, src/services/scheduler-service.ts
- dix dependencies and `scheduler-service`.
=> Fix dependencies

config/default.json, config/env/dev.json, config/env/prod.json, src/services/ipfs-service.ts
Closes #263
Due to issue in ipfs-http-client here: https://github.com/ipfs/js-ipfs/issues/3476
=> fix: pass full url to ipfs config

config/default.json, config/env/dev.json, config/env/prod.json, src/services/blockchain/ethereum/ethereum-blockchain-service.ts
=> feat: allow eth rpc when not on ganache

src/controllers/request-controller.ts, src/models/request-presentation.ts, src/models/request-status.ts
Also present request in a uniform way
=> Request creation is idempotent

src/logger/index.ts
Supports metrics dashboard to show requests per endpoint without the parameter. For example,
```
ip=::1 ts=2021-02-09T01:46:05.572Z method=GET original_url=/api/v0/requests/bagcqceralmt4lv4dmv4fvd26ydtojj3jdr3lea2tiul5dg4o54z4ulu522mq base_url=/api/v0/requests path=/bagcqceralmt4lv4dmv4fvd26ydtojj3jdr3lea2tiul5dg4o54z4ulu522mq http_version=1.1 req_header- status=200 content_length=336 content_type="application/json; charset=utf-8" ref=- user_agent=insomnia/2020.5.2 elapsed_ms=12.596
```
=> feat: add urls (original, base, and path) to morgan logs

.circleci/config.yml
Using dockerhub instead for now
=> ci: remove image build and deploy

config/env/test.json, src/app.ts, src/services/blockchain/__tests__/__snapshots__/eth-bc-service.test.ts.snap, src/services/blockchain/__tests__/eth-bc-service.test.ts, src/services/blockchain/ethereum/ethereum-blockchain-service.ts
No functionality change, just refactoring and increasing test coverage
=> chore(cas): Refactor and unit test EthereumBlockchainService

.github/workflows/build_and_push_ecr.yml
Fix job id name so that variables are set properly when tagging
=> Fix check running anchor process workflow

docker-compose.yml, src/app.ts, src/services/anchor-service.ts
CAS still hanging on clay when it attempts to retrieve a document and a timeout is exceeded.
- Force exits after running the `anchorRequests` method in anchor mode
- Updates the docker-compose file so that anchor and server modes can be tested in containers
=> Hotfix exit anchor mode

package-lock.json, package.json, src/app.ts, src/main.ts, src/repositories/anchor-repository.ts, src/repositories/request-repository.ts, src/services/__tests__/anchor-service.test.ts, src/services/__tests__/db-connection.ts, src/services/anchor-service.ts
I'm *pretty* sure I did this right, and the tests all pass, but this is my first time using TypeORM and I mostly just figured this out from reading the docs, so it would be good if there was someone with more familiarity with it to double check me.  I'm not actually sure who on the team has experience working with TypeORM, so please chime in if you do.  @ukstv @PaulLeCam @v-stickykeys @zachferland @oed @smrz2001
=> chore(cas): Pass database connection in to CeramicAnchorApp

.github/workflows/build_push_publish.yml
Env var was coming up as blank bc it wasn't being set correctly
=> fix(ci): replace = with colons for set output

runner/check-aws-ecs-tasks.js, runner/report-exit.js
Want to have the start and exit messages in dev for debugging missing logs
=> temp: send discord messages for start and exit for all envs

src/services/ceramic-service.ts
When we have a single stream that has had many commits since the last anchor, we build one large multiquery for all the pending commits on that stream.  That multiquery can take a long time to load as each commit is loaded 1 at a time.  There is separate work needed on js-ceramic to parallelize this, but for now as a quick fix we just bump up the timeout.
This also makes the server-side timeout on Ceramic match the client-side timeout the CAS is already using.
=> chore: Increase timeout for multiquery to load streams

src/services/ipfs-service.ts
Implementing the temporary fix from https://github.com/ceramicnetwork/js-ceramic/pull/2065
=> Fix: Disable keep alive for ipfs http agent

src/merkle/__tests__/merkle-metadata.test.ts, src/merkle/merkle-objects.ts, src/merkle/merkle.ts
=> feat: Add version to bloom filter metadata

src/merkle/__tests__/merkle-metadata.test.ts, src/merkle/merkle-objects.ts, src/merkle/merkle.ts
Builds on https://github.com/ceramicnetwork/ceramic-anchor-service/pull/590
=> feat: add stream ids to bloomfilter metadata

src/models/request-presentation.ts, src/models/request-status.ts, src/repositories/__tests__/request-repository.test.ts, src/repositories/request-repository.ts
* Created a function that gathers requests for up to streamLimit streams and marks them as READY
* Undeprecated PROCESSING status
=> feat: atomic request batches

src/repositories/request-repository.ts
=> fix: error when importing typeorm dateutils

src/services/anchor-service.ts
We had [an anchor batch run while prod was being deployed](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Fecs$252Fceramic-prod-cas/log-events/cas_anchor$252Fcas_anchor$252F4357900075cd49198b5400c65c7fea64$3Fstart$3D-172800000)
this caused every request in that batch to fail, which then skipped the CAS summary log so the batch didn't even show up in [the query for seeing all recent anchor batches](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E0$257Estart$257E-172800$257EtimeType$257E$2527RELATIVE$257Eunit$257E$2527seconds$257EeditorString$257E$2527fields*20*40message*2c*20*40timestamp*0a*7c*20filter*20*40message*20like*20*2f*5e*5c*5b.*2f*0a*7c*20pars …
=> chore: Log CAS summary even if no anchors are performed

config/default.json, config/env/dev.json, config/env/prod.json, config/env/test.json, package-lock.json, package.json, src/app.ts, src/controllers/request-controller.ts, src/models/request-presentation.ts, src/services/__tests__/scheduler-service.test.ts, src/services/scheduler-service.ts
* Uses rxjs
* does not use cron
* does not allow overlapping of task
* generic so it can take any task
=> chore: refactor scheduler service

config/default.json, config/env/dev.json, config/env/prod.json, config/env/test.json, package-lock.json, package.json, src/app.ts, src/repositories/__tests__/request-repository.test.ts, src/repositories/request-repository.ts, src/services/__tests__/anchor-service.test.ts, src/services/__tests__/event-producer-service.test.ts, src/services/__tests__/scheduler-service.test.ts, src/services/anchor-service.ts, src/services/event-producer-service.ts, src/services/event-producer/event-producer-service.ts, src/services/event-producer/sqs/sqs-event-producer-service.ts, src/test-utils.ts
* Added Event Producer Service (I used to called it Event Service but that caused problems with tsyringe that i do not understand)
* Added SQS implementation of Event producer Service
* Added createAnchorEventIfReady (not used) 
Should have split this up into a few PRS my bad
=> feat: emit launch anchor event if ready

src/__tests__/ceramic_integration.test.ts, src/app.ts, src/repositories/__tests__/request-repository.test.ts, src/repositories/request-repository.ts, src/services/__tests__/anchor-service.test.ts, src/services/anchor-service.ts, src/services/scheduler-service.ts
* add the scheduler mode
* anchoring READY requests instead of PENDING
* Remove stream limit checks 
* Manually tested scheduler mode
=> feat: add scheduler mode and anchor READY requests

package-lock.json, package.json, src/app.ts, src/services/anchor-service.ts, src/settings.ts
Add prefix 'cas' to cas metrics to distinguish them, also add more anchor metrics
Unit tests
- [ x] The work addresses the description and outcomes in the issue
- [ n/a] I have added relevant tests for new or updated functionality
- [x ] My code follows conventions, is well commented, and easy to understand
- [x ] My code builds and tests pass without any errors or warnings
- [ x] I have tagged the relevant reviewers
- [n/a ] I have updated the READMEs of affected packages
- [ n/a] I have made corresponding changes to the documentation
- [x ] The changes have been communicated to interested parties
Please list relevant documentation (e.g. tech specs, …
=> dependency on the version of metrics package with namespacing

.github/workflows/ci.yml, docker-compose.yml
Possibly fixes the below
```
cas_api_1     | 2022-09-28T23:54:59.041287275Z [2022-09-28T23:54:59.029Z] IMPORTANT: 'Connecting to database...'
cas_api_1     | 2022-09-28T23:54:59.443917387Z [2022-09-28T23:54:59.443Z] ERROR: Error: Database connection failed: QueryFailedError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
```
Problem could be that the cas_api and the cas_anchor service are trying to synchronize the db at the same time
=> fix: CDB-1893 typeorm createConnection failing

src/services/__tests__/anchor-service.test.ts
I did a incomprehensible word dump when creating this test. This should be easier to understand
=> fix: better name for test

migrations/20221031220419_alter_request_add_indexes.js
We do not have any indexes in our database. Hopefully this improves performance
=> feat: Add indexes

src/repositories/request-repository.ts, src/repositories/transaction-repository.ts, src/services/anchor-service.ts
This was not the actual cause of our race condition issues
=> chore: use repeatable read instead of serializable in db transactions

src/services/__tests__/anchor-service.test.ts, src/services/anchor-service.ts
=> fix: skip event if ready requests exists

src/__tests__/test-utils.ts, src/merkle/__tests__/merkle-metadata.test.ts, src/repositories/__tests__/request-repository.test.ts, src/services/__tests__/anchor-service.test.ts
... and some related async -> sync conversion.
=> test: Beautify tests: use sync `randomCID` and `randomStreamID` functions

src/merkle/__tests__/merkle-metadata.test.ts, src/merkle/merkle-objects.ts
Sort leaves by model (`null` last), controller and stream ID. 
Based on https://github.com/ceramicnetwork/ceramic-anchor-service/pull/818.
=> Update Merkle tree leaves sorting logic

docker-compose.yml, src/__tests__/test-utils.ts, src/logger/index.ts, src/merkle/merkle-objects.ts, src/merkle/merkle-tree.ts, src/merkle/merkle.ts, src/repositories/anchor-repository.ts, src/repositories/request-repository.ts, src/repositories/transaction-repository.ts, src/server.ts, src/service-metrics.ts, src/services/anchor-service.ts, src/services/blockchain/ethereum/ethereum-blockchain-service.ts, src/services/event-producer/http/http-event-producer-service.ts, src/services/ipfs-service.ts, src/services/scheduler-service.ts
=> chore: Do not use explicit `public` modifier

.circleci/config.yml, package.json
This does not "solve" the issue but helps prevent it
=> fix: prevent segmentation errors in circleci

src/repositories/request-repository.ts
=> fix: array_position needs explicit varchar type

src/normalize-config.util.ts
Unbundling the PRs into atomic changes.
=> chore: Beautify normalize-config.util.ts

src/app.ts, src/controllers/request-controller.ts, src/services/__tests__/__snapshots__/request-presentation-service.test.ts.snap, src/services/__tests__/request-presentation-service.test.ts, src/services/request-presentation-service.ts, src/services/request-presentation-service.type.ts
=> chore: Beautify RequestPresentation

src/ancillary/did-string.ts, src/models/metadata.ts, src/repositories/__tests__/metadata-repository.test.ts, src/repositories/metadata-repository.ts, src/services/__tests__/metadata-service.test.ts, src/services/metadata-service.ts
=> feat: MetadataService

src/app.ts, src/controllers/__tests__/mock-request.util.ts, src/controllers/__tests__/request-controller.test.ts, src/controllers/request-controller.ts, src/repositories/request-repository.ts, src/services/anchor-service.ts
Completely replaces #853 and #892
=> Last piece of #853: Fill metadata: Change RequestController

migrations/20221004154924_create_anchor_and_request.cjs, migrations/20221004155551_alter_anchor_and_update_rename_columns.cjs, migrations/20221031220419_alter_request_add_indexes.cjs, migrations/20221128160000_add_metadata.cjs, migrations/20221128162000_alter_request_add_origin.cjs
Fixes segfault.
Part of #914 unbundling.
=> chore: Migrations in CJS

src/merkle/merkle-objects.ts, src/services/__tests__/anchor-service.test.ts, src/services/anchor-service.ts
THIS HAS NOT BEEN TESTED. Definitely test this before deploying to prod!
=>  feat: don't do the multiquery to force loading missing commits at all

contracts/Makefile
* chore: Fix foundry
* chore: Fix foundry
* chore: Fix foundry
Include a summary of the change and which issue it addresses in the title of the PR. 
Include relevant motivation, context, brief description and impact of the change(s). List follow-up tasks here.
=> chore: Fix foundry (#931)

src/repositories/request-repository.ts, src/services/anchor-service.ts, src/services/blockchain/ethereum/ethereum-blockchain-service.ts
I want to make it easier to read the logs by being able to filter out the debug/INFO level log messages, so trying to be more intentional about what is marked debug/INFO vs imp/IMPORTANT
=> chore: small logging cleanups

README.md, docker-compose.yml
Using docker-compose for dependencies
=> feat: Run CAS locally, easy way

auth/README.md
The method of deploying cas-auth has changed
- [x ] Verified manually
=> Update README.md with current deploy instructions

.github/workflows/ci-auth.yml, auth/package.json, auth/pnpm-lock.yaml, auth/serverless.yml, auth/src/handlers/api.ts, auth/src/routes/did.ts, auth/src/routes/verification.ts, auth/src/utils/metrics.ts
Because the lambda may not have access to the collector host, we use cloudwatch metric api directly to track metrics.
- [x ] Ran auth tests
- [x ] got auth tests working in pipeline
- [ x] I have added relevant tests for new or updated functionality
- [x ] My code follows conventions, is well commented, and easy to understand
- [x ] My code builds and tests pass without any errors or warnings
- [ x] I have tagged the relevant reviewers
=> Track requests to CAS API gateway

auth/src/handlers/api.ts
Dev artifact/redundant line is resetting increased value to default (100kb).
Include a summary of the change and which issue it addresses in the title of the PR. 
Include relevant motivation, context, brief description and impact of the change(s). List follow-up tasks here.
=> fix (api): remove reset 1mb limit back to default

auth/src/handlers/api.ts, src/server.ts
=> fix: add payload limit to raw body parser

src/ancillary/anchor-request-params-parser.ts, src/settings.ts
This was a requested in a meeting, the metrics should not be able to break anything
=> add metrics for car and legacy requests

package-lock.json, src/services/metadata-service.ts, src/services/request-service.ts, src/settings.ts
We want to track unique writes (updates) per second, possibly by did or model.  Because we may move from pubsub we want to track in CAS.  However, we want to minimize any additional overhead.
=> log writes with metadata with minimum additional overhead

package-lock.json, src/__tests__/ceramic_integration.test.ts, src/__tests__/test-utils.ts, src/app.ts, src/services/__tests__/anchor-service.test.ts, src/services/anchor-service.ts, src/services/ipfs-service.ts, src/services/ipfs-service.type.ts, src/settings.ts
Check if a Ceramic node gets an anchor from witness CAR passed from CAS.
Also, had to pin OpenZeppelin version so that the tests pass. They updated to a solc version to newer than ours.
=> test: Integration test CAR-Ceramic

src/services/request-service.ts
Include the streamId as we can run a later script to pull the genesis commit and get the cacao
Very small change with existing data added to metrics. 
- [ x] Unit tests
=> record the stream id too, we can later get cacao from it

config/default.json, config/env/dev.json, config/env/prod.json, config/env/test.json, src/services/queue/sqs-queue-service.ts, src/utils.ts
Default is 3
Also i noticed that for env vars, the default config does not get used therefore I've set default values in the queue service.
=> feat: add max attempts when polling

docs/DEPLOYMENT.md
As the team grows we should have explicit norms around building and deploying CAS to Clay and Production
It is also desireable to reduce the cycle time for releases if possible to do so safely.
Documentation only, n/a
- [x ] I have tagged the relevant reviewers
- [x ] I have made corresponding changes to the documentation
=> Document release conventions

src/__tests__/test-utils.ts, src/app-mode.ts, src/app.ts, src/logger/index.ts, src/models/queue-message.ts, src/repositories/__tests__/request-repository.test.ts, src/repositories/request-repository.ts, src/services/__tests__/anchor-service.test.ts, src/services/__tests__/ipfs-service.test.ts, src/services/__tests__/witness-service.test.ts, src/services/ipfs-service.ts, src/services/ipfs-service.type.ts, src/services/queue/sqs-queue-service.ts
In the mode pubsub responder, it will listen to pubsub query messages and create an ipfs task to respond with the anchor commit
=> feat: pubsub responder

.github/workflows/ci.yml, config/default.json, config/env/dev.json, config/env/prod.json, src/services/merkle-car-service.ts
Allow Merkle CAR files to be stored using any S3-compatible service.
=> feat: custom s3 endpoint

src/repositories/request-repository.ts
Currently createOrUpdate requests makes two db calls. One to create it, and one to retrieve it. This is causing problems where the request was successfully created but things fail because the retrieval fails. 
```
[2023-11-08T14:14:39.538Z] ERROR: 'Creating request with streamId k2t6wyfsu4pfyyberwn4saz7y39c60x451dk3o3tepu2tpei0n0l4983li6b6s and commit CID bagcqceraqd54g6j2ctt5klgqfidoukyxjxaoimkvugd762cc7v3kyze4cwra from IP: 10.0.1.72 and DID: none  failed: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?'
[2023-11-08T14:14:39.538Z] ERROR: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
at Client_PG.acquireConnection …
```
=> fix: Remove second retrieval in createOrUpdate

Dockerfile
This package won't do anything unless initialized and should be safe for all images.
=> feat: always install datadog package in images

package-lock.json, package.json
This just provides better error logging when metrics fails to start because of invalid parameters
=> upgrade observability package for better error logging

config/default.json, config/env/dev.json, config/env/prod.json, src/services/anchor-service.ts, src/settings.ts
Add metric to record when an anchor is taking too long. This way we can add an alert
=> feat: record when an anchor is taking longer than x minutes 
