ceramicnetwork/ceramic-anchor-service

src/logger/index.ts
src/logger/logger.ts

Splits `index.ts` into `index.ts` and `logger.ts`.  The idea is that when this moves to be its own package, the `logger.ts` will become the `index.ts` of the new `logger` package.  And then any other packages that want to use the new logger package (the cas, the rest of js-ceramic) will need something like the current `index.ts` to configure and export specific logger instances as needed for the specific package.
I guess that means that the js-ceramic monorepo will need a place to export the specific `logger` instances it needs, someplace other than the `@ceramicnetwork/logger` sub-repo.  I guess I will add a logger.ts file to the `common` package to do that.

chore(cas): Cleanup logger to prepare it to be its own package

---

src/server.ts

Related to #295 and allows us to see requests per origin properly in metrics

feat: get forwarded ip in access logs

---

.circleci/config.yml

CI is failing because the cluster it is trying to deploy to no longer exists

ci(fix): temporarily remove deploy step

---

src/logger/index.ts

Access logs should match formatting of other logs. Also want the file name to match what we have in js-ceramic.
- Change file name to 'http-access.log'
- Use service logger for morgan middleware (as we do in js-ceramic)
Related to metrics dashboard updates for the file name https://github.com/3box/ceramic-stats/commit/b4d1462fadad40e8a2e5445cde55dc72b0bb9726

feat(breaking): change access log to http-access

---

config/default.json
config/env/dev.json
config/env/prod.json
config/env/test.json
src/services/blockchain/__tests__/__snapshots__/eth-bc-service.test.ts.snap
src/services/blockchain/__tests__/eth-bc-service.test.ts
src/services/blockchain/ethereum/ethereum-blockchain-service.ts
src/utils.ts

This change increases the rate at which the ethers library will poll infura from every 4 seconds to every 15 seconds (just over the block production rate), and adds a 1 hour timeout to how long we wait for each submitted transaction to be mined.
There is one failure mode I'd like help thinking through whether or not this is a security concern and if there's anything we can do to mitigate it.  What if we submit a transaction that doesn't get mined (let's say because gas price is too low).  We time it out after an hour and retry up to 3 times (recalculating gas price each time).  But after the final retry times out, we declare the transaction failed and move on.  The anchor batch is declared a failure, and the pending CIDs to be anchored stick around in the database and get picked up in the …

fix(cas): Add timeout to how long we wait for eth transactions to get mined

---

src/services/blockchain/__tests__/eth-bc-service.test.ts
src/services/blockchain/ethereum/ethereum-blockchain-service.ts

ether's `BigNumber` package doesn't like decimals, so this changes the math from multiplying by .01 to dividing by 10

fix(cas): Fix underflow error in gas price math

---

src/services/ceramic-service.ts

Don't stall forever if the document doesn't load for whatever reason.

hotfix: timeout on document load after 60s

---

.circleci/config.yml

This is needed because CAS clay is still using the ECR image tagged develop. So this builds the ECR image for it to use when changes are merged into `main` so that the clay instances get the new image.
This code will be removed once we clean up the pipelines here.

fix(ci): build docker image on main branch

---

src/app.ts
src/services/ceramic-service.ts

Clay CAS instances are hanging on our infra (AWS ECS) even though it seems like all the node processes should have exited. Testing locally if loading a doc fails execution would continue but the process would not exit until after the timeout of 60s. However, on our infra it seems that the introduction of this timeout keeps the process running indefinitely.
I believe this change helps the issue by clearing the timeout (because we aren't seeing this issue on dev), but I can't be sure until we run it on ECS. If it still hangs it is likely we need to make an explicit call to `process.exit()` after anchoring.
- Clears `setTimeout` if `loadDocument` resolves or rejects
- Cleans up the execute anchor code to be a bit neater
- *We are seeing out of order log messages because the anchor service …

Hotfix: Exit anchor mode

---

src/services/ceramic-service.ts

Otherwise tests fail because of a type error

fix: timeout type should be any

---

Dockerfile.runner
runner.sh
runner/check-aws-ecs-tasks.js
runner/package.json

Having multiple CAS anchor modes running leads to failed batches.
This introduces a new Dockerfile that allows us to run a script to check if AWS ECS has any anchor processes running. If so we exit without starting another CAS anchor process. Otherwise we proceed with starting CAS in anchor mode.
Build this image in CI and push it to AWS ECR

Check running anchor process

---

.github/workflows/build_and_push_ecr.yml

1. We are moving away from using CircleCI so this will replace the existing workflow that we have configured there
2. We want to build a new docker image for CAS that uses the "CAS runner" (see: #338)
- Adds github workflow that builds image on push or when manually triggered
- Have a feature branch in the workflow so we can test this without needing to merge to develop each time, but this needs to be merged in first on develop in order for the action to be available for testing on other branches. (Just how github actions works).

feat(ci): add workflow to build and push ecr image

---

runner/check-aws-ecs-tasks.js

When we detect if a task is running it is seeing itself running then exiting. So we need to check if any *additional* tasks are running.

fix: run anchor mode if only 1 task is running

---

.github/workflows/build_and_push_ecr.yml

Adds tnet as an image tag when on main branch. This way in our infra the tnet environment can use the image tagged with tnet. If we want to do RCs for CAS in the future this will make it possible.

tnet image tag

---

Dockerfile.runner
runner/check-aws-ecs-tasks.js

Current behavior:
If an anchor task spins up when at least one task is already running, the task exits without anchoring.
New behavior:
Before exiting a discord message will be sent to the alerts channel indicating that the latest anchor task has not completed by the time the next one is scheduled to start.
- Relies on infra update to add discord webhook url env var https://github.com/3box/ceramic-infra/commit/40d12cdc8aff8315dc9a9e786fb6eaab3c72a99b

feat: send discord notif if anchor hangs

---

src/services/anchor-service.ts

It may be easier to review this PR by reviewing the two commits that go into it one at a time. The first refactors the code without any functionality change, the second changes the way we load streams to add parallelism.

fix(cas): Load candidate streams in parallel batches

---

src/services/blockchain/ethereum/ethereum-blockchain-service.ts

This most likely would have made last night's mainnet CAS anchor batch succeed

fix(cas): Always confirm all previous txn attempts after nonce error

---

.github/workflows/build_and_push_ecr.yml

Clean (and speed) up build and pushing docker images to prevent accidental updates and keep track of revisions better
Not using Dockerhub's automate build tool anymore. Instead added logic here to build the CAS image used by the anchor task and push it to Dockerhub

CI build and push to dockerhub

---

src/controllers/request-controller.ts

This makes Ceramic throw an exception rather than just return that the anchor failed, which complicates the error handling code paths

fix(cas): Don't use bad HTTP status when request doesn't exist

---

Dockerfile

* use `npm ci`, instead of `npm install` so the dependency versions are always locked.
* By copying only `package.json` and `package-lock.json` as a separate step, we reuse cache for 'npm ci' (ie, npm install).
- This saves build time, bandwidth when we are doing docker build as the way to test locally for new developments (if any).
- Specially helpful when the resulting image is immediately tested with clayground.
- This also improves the build time.
Signed-off-by: Amar Tumballi <amar@dhiway.com>

fix: optimize build time during (repeat) docker builds

---

package.json
src/app.ts
src/controllers/request-controller.ts
src/main.ts
src/models/request-presentation.ts
src/repositories/request-repository.ts
src/server.ts
src/services/__tests__/anchor-service.test.ts
src/services/anchor-service.ts
src/services/blockchain/__tests__/eth-bc-service.test.ts
src/services/blockchain/ethereum/ethereum-blockchain-service.ts
src/services/ceramic-service.ts
src/services/ipfs-service.ts
src/services/scheduler-service.ts

Instead of relying on the global dependency injection `container` object, pass the container explicitly.
Instead of relying on the global `config` object, register the config with the dependency injection container and resolve it wherever needed.
Not the cleanest, but seemed the shortest path to allowing multiple CAS instances to coexist in the same process space

chore(cas): Do not rely on process wide globals

---

src/models/request-presentation.ts

As requested by Sergeys in the PR https://github.com/ceramicnetwork/js-ceramic/pull/1649. To maintain the backwards compatibility anchorCommit field was added besides the anchorRecord.
This PR also will resolve the issue stated in https://github.com/ceramicnetwork/ceramic-anchor-service/issues/485

Rename anchorRecord to anchorCommit

---

src/services/blockchain/__tests__/__snapshots__/eth-bc-service.test.ts.snap
src/services/blockchain/__tests__/eth-bc-service.test.ts
src/services/blockchain/ethereum/ethereum-blockchain-service.ts

Use more straight-forward calculation of maxFeePerGas. It does not depend now on previous transaction fee.

feat: Recalculate maxFeePerGas via baseFee

---

runner/check-aws-ecs-tasks.js

Sends CAS hanging alerts to alerts-ceramic Discord channel instead of the warnings channel when in prod environment.
Test in prod!
https://app.zenhub.com/workspaces/platform-611996cb76d3b50013bfb993/issues/3box/ceramic-infra/480

feat: send prod hanging messages to alerts

---

runner.sh
runner/check-aws-ecs-tasks.js
runner/report-exit.js
runner/report-failure.js

When in the prod environment, send a message to discord when a CAS anchor task starts and ends
Test in prod!

feat: send discord messages on start and exit

---

src/services/anchor-service.ts

this will make batches far more likely to be under-full, but avoids ever anchoring requests out of order

fix: don't ever pull in newer requests over older ones

---

src/services/anchor-service.ts

It's overly verbose, and now that we pull in all pending requests, the log line has gotten so long it seems to have passed some maximum in Log Insights - Log insights is breaking the line up into multiple lines, which is breaking some of the saved queries we use to get reports on what the batch did

chore: Do not log every single request ID in batch summary message

---

src/services/anchor-service.ts

Doesn't break anything, just how many unprocessed requests we report at the end of a batch

fix: fix unprocessed request reporting

---

src/services/anchor-service.ts

Many anchor batches fail to load the first one or two streams at the beginning of the batch with an error like
```
`Failed to load stream k2t6wyfsu4pg0eat56bbz0hb2uk4w1oogh24munj6wsnfqaymyzv6k5akske13: Error: HTTP request to 'https://ceramic-private-cpc.3boxlabs.com/api/v0/streams/k2t6wyfsu4pg0eat56bbz0hb2uk4w1oogh24munj6wsnfqaymyzv6k5akske13?pin=true&sync=0' failed with status 'Internal Server Error': {
"error": "Request timed out"
}`
```
My suspicion is that the recently-restarted ipfs/ceramic nodes haven't fully stabilized after startup yet, due to the tight restart loop we have in place.  My hope is that giving an extra minute before contacting ceramic/ipfs at the beginning of a batch will eliminate these failed requests.

fix: Sleep one minute at startup for ipfs to stabilize

---

package-lock.json
package.json

I'm not actually sure why npm seems to be installing version 1.3.4 of this package currently instead of the most recent 1.3.9.
Whatever the reason, it saved us as version 1.3.7 introduced a breaking change to the bloom filter data format.
For now, let's pin to version 1.3.4 so we make sure we don't accidentally start using the newer version of the bloom-filters pacakge until after https://github.com/ceramicnetwork/ceramic-anchor-service/issues/566 is complete, which will enable us to upgrade as we'll be able to keep track of which version was used for each filter we create

chore: Pin bloom-filters package to version 1.3.4

---

.github/workflows/ci.yml
.gitignore
Dockerfile

This PR implements a new CI pipeline using [Dagger](https://dagger.io/).
This allows the various Ceramic component pipelines to be written entirely agnostically of the pipeline service (e.g. GitHub Workflows).
Dagger is still a little rough around the edges so some of the syntax is non-intuitive. However, as they improve their DX, we'll be able to clean this code up as well.
I've decided to keep the actual pipeline [Dagger plan](https://docs.dagger.io/1202/plan) in a [separate repository](https://github.com/3box/pipelinetools) that can be used from other Ceramic repos instead of scattering the code across the repos.
I have intentionally not deprecated the old pipeline (CircleCI, building an image, posting to Lambda, etc.) until the new one can run correctly end-to-end in parallel.
Tasks …

feat: new ci

---

src/repositories/__tests__/request-repository.test.ts
src/repositories/request-repository.ts
src/services/__tests__/anchor-service.test.ts

Retry failed anchor requests in every subsequent batch up to 48 hours after the request was created. Should help us be more resilient to transient networking errors and reduce the frequency of anchor requests failing entirely (at the risk of anchoring requests out of order, which could break 3IDs, but matters less with did:pkh)

Fix: findNextToProcess includes failed

---

src/__tests__/ceramic_integration.test.ts
src/services/anchor-service.ts

The "Consensus for anchors" integration tests periodically fail. It seems that the CAS is not anchoring the latest update. My suspicion (could not reproduce locally) is that the CAS ceramic node isn't receiving the latest update before the anchor. So my fix is to wait for the latest update and then anchor. Timing in tests is a very tricky thing. This may not work but we won't really know until we try.

Fix: flaky ceramic integration tests

---

src/app.ts

Ok so probably should have made explicit parameters but this package is used in several places
So just fix and use the correct name in the config object 

correct parameter name for metrics start

---

.circleci/config.yml
contracts/Makefile
package-lock.json

This fixes the broken steps of the pipeline for building contracts, and cas
Small PR to fix issues in our pipeline for building the contracts. The contract building was failing because we were installing the deps as a the ```circleci``` user, but then trying to invoke the NPM script as ```root```. Since we were setting the PATH with $HOME, using ```sudo``` changes that ```$HOME``` directory to like ```/home/root``` etc
```yaml
- run:
name: install dependencies
command: |
curl -L https://foundry.paradigm.xyz | bash ## installing as circleci ##
echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> /home/circleci/.bashrc
source /home/circleci/.bashrc
echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> $BASH_ENV
source $BASH_ENV
foundryup
forge --version
- run:
name: build contracts
command: |
echo …
```

CI/CD integration fixes for the build contacts, and build cas steps

---

src/repositories/__tests__/request-repository.test.ts
src/repositories/request-repository.ts

I get all stream Ids that need to be anchored. Then i retrieve all requests associated with those streamIds. These requests include completed/failed/processing requests etc. It should not

fix: Only mark relevant requests as ready

---

contracts/Makefile
contracts/src/CeramicAnchorServiceV2.sol
contracts/test/CeramicAnchorServiceV2.t.sol
src/services/blockchain/__tests__/eth-bc-service.test.ts
src/services/blockchain/ethereum/ethereum-blockchain-service.ts

I discard the first 4 bytes of the CID [version, code, hash code, digest size]. This is 2 more bytes than described in the ticket. Please let me know if this is okay.

feat: use bytes32 in smart contract

---

package-lock.json
package.json

The CAS api node failed to run in dev with the error `Error [ERR_LOADER_CHAIN_INCOMPLETE]: "ts-node/esm 'resolve'" did not call the next hook in its chain`
@ukstv suggested switching to TSM loader to avoid this issue.  See https://linear.app/3boxlabs/issue/PLAT-853/consider-moving-from-ts-node-to-tsm for further details.
Able to run `npm run start` after switching to tsm loader locally.  Need to test on dev, should we test by another method than deploying to dev?

switch to tsm loader - #PLAT-853

---

runner.sh
runner/report-start.js

Fixes a bug where the app doesn't start because `npm run start` doesn't get called.
This PR adds back the console log which is checked before running the npm script.
Tested locally with docker, was able to repro and see the fix work.

fix(runner): log ok to start app

---

README.md
docker-compose.yml

This PR fixes docker compose so that CAS properly connects to the IPFS container that gets spun up.
This also fixes our CI which tries to use docker compose to do image verification.
- When ipfs-http-client is used to subscribe to pubsub, it makes an http request to IPFS but expects the uri to start with http or https.
- Also the port used by ceramicnetwork/ipfs-daemon is 5011, not 5001.
Tested locally and was able to repro the issue and see the fix work.
Broken
Working

Fix Docker Compose

---

package.json
src/merkle/__tests__/merkle-metadata.test.ts
src/merkle/merkle-objects.ts
src/services/__tests__/anchor-service.test.ts

```
[2022-09-20T14:42:09.433Z] ERROR: 'Error when anchoring: Error: Merkle tree cannot be created: TypeError: candidate.metadata.controllers is not iterable' Will look into fixing
```
No tests because that is a larger effort (adding to the ceramic_integration repo and setting up all the model stuff)

fix: Use stream's state metadata to generate merkle tree metadata

---

config/default.json
src/services/__tests__/anchor-service.test.ts
src/services/anchor-service.ts

Originally we wanted the min stream count = max stream count aka only anchor when we have a 1024 streams or streams are expiring.
This means that we will have to set MIN_STREAM_COUNT to something in dev and prod otherwise it will default to 1 (default.json)

fix: use min stream count when marking requests as ready using the scheduler

---

.circleci/config.yml

Just rename the test workflow so that it is more obvious what is running in the github ui

ci: rename test workflow

---

src/repositories/__tests__/request-repository.test.ts
src/services/blockchain/__tests__/eth-bc-service.test.ts

If all entries are updated at the same time, then when you go to retrieve them (ordered by updatedAt desc) the order returned is unpredictable. 
Also I'm removing the block timestamps upper bound check. Its too unreliable

fix: flaky test timing

---

src/merkle/merkle-objects.ts
src/repositories/request-repository.ts
src/services/__tests__/anchor-service.test.ts

Use serializable isolation level to prevent concurrent updates from making unpredictable updates
Check if the newest request was already anchored, if so mark all those requests as anchored

fix: serializable isolation lvl and already anchored check

---

src/repositories/__tests__/request-repository.test.ts
src/repositories/request-repository.ts
src/services/__tests__/anchor-service.test.ts
src/services/anchor-service.ts

When updating expiring ready requests we were not using a db transaction. 
1a. Scheduler service gathers expired ready requests which include requestA
1b. requestA is at the SAME time being updated to PENDING and added to a batch
2. all requests gathered in step 1a are updated to READY via the scheduler service
requestA should have status PENDING but because of step 2 it is READY
3a. The scheduler service gathers expired ready requests and thinks requestA is READY and expired
3b. The batch completes and requestA is at the SAME time being updated to COMPLETED
4. All requests gathered in step 3a are updated to READY via the scheduler service
requestA should have status COMPLETED but because of step 4 it is READY
Not ideal at all so I put steps 1a + 2 into a db transaction to prevent the …

fix: use db transaction when updating expiring ready requests

---

src/controllers/anchor-controller.ts
src/controllers/request-controller.ts
src/repositories/request-repository.ts
src/service-metrics.ts
src/services/anchor-service.ts
src/settings.ts

In the request-repostiory add metrics to findAndMarkReady to monitor how long a request takes to be marked as READY (now - createdAt) (not sure if we want average or a range or  the longest)
In the request-repository add metrics to findAndMarkAsProcessing to monitor how long a request takes to be marked as PROCESSING (now - updatedAt) (not sure if we want average or a range or  the longest)
Also addresses overall timing between request and anchor (PLAT-844)
- [ x] The work addresses the description and outcomes in the issue
- [ x] My code follows conventions, is well commented, and easy to understand
- [ x] My code builds and tests pass without any …

Metrics on Anchor Request Timing

---

src/merkle/__tests__/merkle-metadata.test.ts
src/merkle/merkle-objects.ts

Adds the `model` id to the bloom filter if available and remove the `schema`, `family` and `tags`. 

Add model to bloom filter + remove schema, family and tags

---

docker-compose.yml

Updated docker-compose to use `goerli` network.
Previously, the image verification used `ropsten` network. The network is no longer supported, so `ethers` returns no default provider for it.

chore: Use goerli network in docker-compose

---

config/default.json
config/env/dev.json
config/env/prod.json
config/env/test.json
src/services/ceramic-service.ts

The goal is that we can set this down on clay (probably to 1 second) so that Clay batches won't take so long to complete (given that we get a lot of stream load timeouts on clay, where it is more expected)

feat: Let load stream timeout be configurable

---

src/repositories/request-repository.ts

Not visible in testing here, but visible when moved [from tsyringe](https://github.com/ceramicnetwork/ceramic-anchor-service/pull/827)

fix: Subtle constraint-related bug

---

src/services/__tests__/anchor-service.test.ts
src/services/anchor-service.ts

Very unlikely to happen but if the creating the anchor commit on ipfs step fails, we could have no anchor commits to insert into the db. And that is what we saw in QA.

fix: check for empty anchors

---

src/controllers/__tests__/request-controller.test.ts
src/controllers/request-controller.ts
src/models/request.ts

The origin IP address is retrieved and parsed from `X-Forwarded-For` http header, according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#parsing

Feat/fill the origin CDB-2016

---

config/default.json
config/env/dev.json
config/env/prod.json
src/services/anchor-service.ts

I haven't added config options to CAS before so not fully sure if I've covered all the changes. Please let me know if I've missed something.
Also, is this something I should add a unit test for? `anchor-service.test.ts` seemed like the right place, if so.

fix: make block info in anchor proof configurable

---

src/services/anchor-service.ts

This hasn't been tested at all, please review carefully in case I missed anything

fix: Optimize multiquery to only load newest missing request

---

src/services/ceramic-service.ts

This will help push the time spent resycing streams with CACAO errors to happen out-of-band when requests come in, rather than during the anchor batches as they run.

fix: use loadStream with SYNC_ON_ERROR flag for pinning

---

src/services/anchor-service.ts

cleaning up the logging given the behavior change from https://github.com/ceramicnetwork/ceramic-anchor-service/pull/901

chore: Clarify log message when requests are missing from stream log

---

src/services/anchor-service.ts
src/services/ceramic-service.ts

We'll still try to pin the stream during request creation in the API server

fix: don't pin when loading stream for anchor worker

---

auth/src/authorizers/default.ts
src/auth/index.ts

I found a few issues with CAS auth in dev. After applying these fixes to a [temporary image](https://github.com/ceramicnetwork/ceramic-anchor-service/tree/temp/debug) I did not see any unrecognizable errors.
- Get use `digest` property from signed payload instead of body (to match [how js-ceramic creates payload](https://github.com/ceramicnetwork/js-ceramic/blob/eb179830da3b5396794e85a5df374c7fc1590829/packages/core/src/anchor/auth/did-anchor-service-auth.ts#L49-L53))
- Check if `req.body` is an empty object in auth middleware (skip verification if so)
- Add return statements so `next` is not called twice in auth middleware

CAS Auth Fixes

---

config/default.json
config/env/dev.json
config/env/prod.json
package-lock.json
package.json
src/services/__tests__/ipfs-service.test.ts
src/services/ipfs-service.ts
tsconfig.json

Right now if we get a spike of concurrent request to the CAS API, it can overwhelm the IPFS node, causing the node to have a huge memory spike and crash (see grafana screenshots below).  Instead of sending more requests to IPFS than it can handle, we can slow down the processing of incoming requests to avoid overloading the IPFS node.

Rate limit access to IPFS to avoid overloading it

---

src/controllers/request-controller.ts

deployment of cas-auth changed the way ip addresses are recorded
we can use the new parseOrigin function to replace them (sometimes it is did, sometimes it is ip addr). 
- [x ] unit tests
TBD - after this merges will update the grafana

record the source ip or did

---

auth/src/authorizers/ipAllowlist.ts

We want to ensure Hirenode does not run into rate limits during the Gitcoin round.
Will merge this directly to main, deploy to prod cas-auth, then we can merge back to develop.

add the ip for gitcoin hirenode

---

.github/workflows/ci-auth.yml
auth/src/authorizers/default.ts

The change to include the sourceIp in a context field needed to also be made in the permissioned ip pathway. 
- [x ] unit tests
- [x ] My code follows conventions, is well commented, and easy to understand
- [ x] My code builds and tests pass without any errors or warnings
- [ x] I have tagged the relevant reviewers
- [ x] I have made corresponding changes to the documentation (already changed the metrics to pull this)

add context with source ip into permissioned ip address pathway

---

.github/workflows/ci-auth.yml
auth/src/authorizers/default.ts

cherry-pick 87b62b23361cf537b72bc45bb690c40d7dcc61e7
From https://github.com/ceramicnetwork/ceramic-anchor-service/pull/1020
* add context with source ip into permissioned ip address pathway
* see if no-frozen-lockfile fixes it
The change to include the sourceIp in a context field needed to also be made in the permissioned ip pathway.
[x ] unit tests
[x] deploy to dev and verified that source_ip shows up in logs now for cas api

add context with source ip into permissioned ip address pathway (#1020)

---

package-lock.json
package.json
src/controllers/request-controller.ts
src/services/ipfs-service.ts
src/settings.ts

See ticket - we want metrics when an anchor request is not created, separately from when the anchor itself fails.
Note that the current cloudwatch query that tracks this mainly is reporting IPFS failures.  Also added metrics to specifically track ipfs failures vs successes as we may want that ratio as well.
- [ x] unit tests
- [ x] The work addresses the description and outcomes in the issue
- [ x] My code follows conventions, is well commented, and easy to understand

add metrics on failure to create requests and on ipfs success/fails

---

auth/src/handlers/api.ts

Partner discovered issue when sending CAR files that resulted in an internal server error. Decided to increase JSON parsing size from default 100kb to 1MB to address the issue.

fix (api): Increase JSON payload size to 1MB

---

config/default.json
config/env/test.json
src/db-connection.ts

Currently if you would like to use a local db for tests, it has to have a specific configuration (test-db, test-user, etc. Now you can use the db url you provided with any configuration you want.

chore: use DATABASE_URL for the db connection if set in tests

---

src/services/__tests__/anchor-service.test.ts
src/services/anchor-service.ts

We do not want to anchor replaced requests. This will reduce the batch size. But will ensure the latest commit will be anchored.

fix: Ignore replaced requests when anchoring batches

---

src/repositories/__tests__/request-repository.test.ts
src/repositories/request-repository.ts

To `Replaced by ${cid of more recent commit}`

chore: Update message for a replaced anchor

---

src/services/__tests__/anchor-service.test.ts
src/services/anchor-service.ts
src/settings.ts

Nack a whole batch if failed to store a Merkle CAR to S3 or IPFS, log an error.

feat: Failed status is terminal

---

package-lock.json
package.json

So, we need to update the observability package (there was an issue of prometheus no longer converting : chars to _ taht messes up our historical metrics - this converts to _ in all cases) to 1.4.0
also cleaning out .swp files

update the observability package for consistent metric naming

---

src/services/anchor-service.ts

It is very weird that in kubernetes the default config does not populate sqsQueueUrl

fix: do not assume default sqs queue url

---

src/app.ts
src/services/request-service.ts

This is a small PR that does 2 things:
1) changes the name from 'cas-[mode]' to 'cas_[mode]', because previously the '-' char was being auto-converted to an underscore, but now its not clear if that will happen or not.  So setting it explicitly to underscore to avoid possible name-change issues.
2) adds a log as well as metric to see if the createOrUpdate function is called as expected.  This will also give us a second check on the metrics which are a key KPI

log cas writes as well as issue a metric

---

src/ancillary/anchor-request-params-parser.ts
src/controllers/request-controller.ts

Log the necessary fields.
FYI The failure is due to a version update in open zeppelin contracts repository. Fixed in https://github.com/ceramicnetwork/ceramic-anchor-service/pull/1096/commits/e41a479b0c8a463a2dc238b3a23436df10ba4650 as part of https://github.com/ceramicnetwork/ceramic-anchor-service/pull/1096

chore: Log an incoming request properly

---

src/services/merkle-car-service.ts

I fucked up. We try to store `Uint8Array` to S3 which [gets turned into String](https://github.com/loune/s3leveldown/blob/master/s3leveldown.js#L240) of numbers like `58,62,101,114, ...`, like what happens when you do `String(uint8array)`. The PR amends that.

fix: Store bytes to S3

---

config/default.json
config/env/dev.json
config/env/prod.json
config/env/test.json
package-lock.json
package.json
src/app.ts
src/services/request-service.ts

read env variables for the metrics export intervals and timeouts, so that we can adjust quickly in case needed without redeploy
It is not clear why the metrics show up and then disappear, but adjusting the timeout to the OTLP default may be the first step
Also include all the desired data in the log message so that we could potentially switch to pulling the data we need from logs instead of the collector.

configurable export intervals and better logging

---

config/default.json
config/env/dev.json
config/env/prod.json
config/env/test.json
src/app.ts
src/services/__tests__/task-scheduler-service.test.ts
src/services/anchor-service.ts
src/services/queue/sqs-queue-service.ts
src/services/task-scheduler-service.ts

Please use environment vars:
APP_MODE=continual-anchoring
SCHEDULER_STOP_AFTER_FAIL=true
to turn this on

feat: stop continual anchoring if we receive an empty batch

---

src/controllers/__tests__/request-controller.test.ts
src/repositories/__tests__/request-repository.test.ts
src/repositories/request-repository.ts
src/services/__tests__/fake-factory.util.ts
src/services/request-service.ts

Imagine a Ceramic node updates a stream with commit A and tries to request an anchor for commit A from the CAS, but the CAS is temporarily unavailable, say due to the network being down transiently.  The Ceramic node will then start a background task to retry creating the request once every 60 seconds until it goes though.  Then, 30 seconds later, the stream is updated again on the same node, with commit B.  By this point the network has recovered, and the request for commit B is successfully created against the CAS.  Then 30 seconds after that, the anchor request for commit A is retried and goes through.
We have a timestamp inside a request, so commit B still trumps commit A, but we have a bug (or maybe not @stephhuynh18 thanks to CASv5) as we consider REPLACED to be applied to previous …

fix: REPLACE all previous

---

src/ancillary/__tests__/anchor-request-params-parser.test.ts

This reverts commit d82ee7bc22c5ae9f984b13b2d0140b04a8ca268b.
add test for invalid carfile having 'left' signal

Revert "move invalid carfile tests to separate PR"

---

config/default.json
config/env/dev.json
src/app.ts

When the env var `METRICS_PROMETHEUS_PORT` is set, listen for prometheus metric requests on that port.
Include relevant motivation, context, brief description and impact of the change(s). List follow-up tasks here.
This is an alternative solution to pushing metrics to a opentelemetry collector.

feat: enable prometheus endpoint when the port is set

---

config/default.json
config/env/dev.json
config/env/prod.json
src/repositories/__tests__/request-repository.test.ts
src/repositories/request-repository.ts
src/services/__tests__/ipfs-service.test.ts
src/services/ipfs-service.ts

We have gotten into a scenario where we were receiving anchor status requests for really old streams/cid combos. In light of this as a safeguard lets only respond to anchors happening in the last three months. Though this is configurable so can be easily changed.

feat: add pubsub responder window

---

src/db-connection.ts

Configure a connection for knex for 3-30. It appears to be using the default, which is 2-10.

Set a knex pool size to 3 - 30

---

config/default.json
config/env/dev.json
config/env/prod.json
config/env/test.json
src/__tests__/ceramic_integration.test.ts

The CAS doesn't use Ceramic nodes anymore

chore: Remove unused Ceramic nodes from test

---

src/app.ts
src/services/__tests__/task-scheduler-service.test.ts
src/services/task-scheduler-service.ts
src/settings.ts

Before: retry 3 times before erroring out
After: no retries, better for debugging
Tested:
tested manually
altered unit test

feat: exit with error when an anchor worker fails to anchor a batch

---

src/auth/index.ts

Removing console logs that are bulky and unecessary

chore: remove bulky logs

---

src/controllers/request-controller.ts
src/services/request-service.ts
src/settings.ts

add metric to cas for anchor accepted
- [x ] unit tests
metrics generally will not have prod impacting failures

add metric for anchor accepted

---

Dockerfile
config/default.json
config/env/dev.json
config/env/prod.json
config/env/test.json
entrypoint.sh
package-lock.json
package.json
src/__tests__/ceramic_integration.test.ts
src/app.ts

The current CAS metrics are being sent from the 6 different api nodes with the same name and labels, resulting in inaccurate metrics, stepping on totals, odd reset patterns.  Each instance should have a distinct label.  This PR uses the task id as the label and uses the new observability functionality of Instance Identifier to automatically label all metrics (see https://github.com/ceramicnetwork/observability/pull/29)
- [ x] observability package new unit tests
- [ x] I have added relevant tests for new or updated functionality
Please list relevant documentation (e.g. tech specs, …

add capability to set an instance identifier which labels all metrics

---

auth/pnpm-lock.yaml
auth/serverless.yml
auth/src/authorizers/default.ts

During load testing on CAS, we're getting error "EMFILE: too many files open".

fix: move db connection outside handler, too many open files

---

src/repositories/repository-types.ts
src/repositories/request-repository.ts
src/services/anchor-service.ts

Fixes error "could not serialize access due to concurrent update". This is the only place that does not catch this error and retry

Fix: retry db transaction if we get a serialization error when persisting anchors

---

src/services/request-service.ts

The metrics ending in _tsdb were intended to be routed thru promscale container and directed to timescaledb; however, this had not worked reliably and we actually get them from logs instead.  Removing this path entirely as it might be bogging down the collectors.  
Also adjusted the priority of the business metric logging from `debug` to `imp` as a signal that we should not remove or change it without carefully looking at dependencies.

remove the high cardinality timescaledb-intended metrics as we get these from logs now

---

runner/report-exit.js
runner/report-failure.js
runner/report-start.js

Explicitly exit the runner scripts once they are complete.

fix: exit runner scripts explicitly once completed

---

Dockerfile

We were only injecting it into the Workers before.

fix: inject ecs task id into api

---

package-lock.json
package.json

the json parsed parameters for intervals were being passed thru as strings

bump observability to a version that enforces numeric params

---

config/default.json
config/env/dev.json
config/env/prod.json
config/env/test.json
src/services/anchor-service.ts
src/services/queue/sqs-queue-service.ts

Allow workers to be able to pull anchor batches from S3, with fallback to existing logic for extracting batches from SQS messages.
This needs to be merged before S3 batching in the Scheduler is merged, since this code is backward-compatible and capable of handling both types of batching strategies.

feat: cas scaling ph 2 (s3 batching)

---

src/repositories/__tests__/metadata-repository.test.ts
src/repositories/anchor-repository.ts
src/repositories/anchor-repository.type.ts
src/repositories/metadata-repository.ts
src/services/anchor-service.ts
src/services/metadata-service.ts

Currently we loop through each request and retrieve the metadata for it, and check if there is an anchor for it. Instead of doing this per request, we can do one batch call to do it before processing.

feat: batch db calls when loading candidates

---

src/services/queue/sqs-queue-service.ts

SQS sendMessages  is taking  >3 minutes. We are increasing the number of socket connections sqs can make and adding a config to allow it to reuse connections.
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-maxsockets.html

feat: reuse connections in http client + increase max sockets

---

src/ancillary/multiprocess.ts

If env variable `MULTIPROCESS_SIZE` (as a decimal number) is set, it takes precedence over nodejs `cpus().length` of `node:os`.
That should fix a bug of "having" 32 processors on k8s regardless of the underlying number of CPUs.

feat: Use env variable to configure number of workers
